# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: true

cran: https://cran.rstudio.com

# until generics is finalized
warnings_are_errors: false

r:
  - 3.5
  - 3.6
  - devel

matrix:
  allow_failures:
    - r: 3.3       # inum      install failure (seg fault)
    - r: 3.2       # partykit  install failure (libcoin needs >= 3.4.0)
    - r: 3.4       # mvtnorm   requires >= 3.5.0

cache:
  packages: true

env:
  global:
  - MAKEFLAGS="-j 2"

